In [ ]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_tech.csv", encoding="utf-8", low_memory=False, sep=",")
#display(df_vendas)
display(df_vendas.info())

df_analise = df_vendas.drop(columns="Data_Base")
df_analise["Loja"] = df_analise["Loja"].fillna("Online")
df_analise["Loja"] = df_analise["Loja"].str.strip()
df_analise["Loja"] = df_analise["Loja"].str.title()
df_analise["Data"] = pd.to_datetime(df_analise["Data"], format="%Y-%m-%d")
df_analise = df_analise.drop_duplicates(subset="ID_Pedido", keep="last")

display(df_analise.info())
display(df_analise)

display(df_analise["Preco_Unitario"].describe())

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 6.1 MB

None

<class 'pandas.DataFrame'>
Index: 100000 entries, 0 to 100099
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 6.1 MB

None

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274

count    100000.000000
mean       1999.780100
std        1840.918232
min          40.000000
25%         120.000000
50%        1200.000000
75%        3200.000000
max        5500.000000
Name: Preco_Unitario, dtype: float64

In [44]:
import pandas as pd
import numpy as np

df_data = pd.read_csv('data.csv')
display(df_data.info())
df_analises = df_data

df_analises["cidade"] = df_analises['cidade'].fillna("Não Informado")
df_analises["cidade"] = df_analises['cidade'].str.strip().str.title()
df_analises["data_compra"] = pd.to_datetime(df_analises["data_compra"], errors="coerce", format="%Y-%m-%d")
df_analises["data_compra"] = df_analises["data_compra"].fillna("Não Informado")
df_analises["idade"] = pd.to_numeric(df_analises["idade"], errors="coerce")
df_analises["idade"] = df_analises["idade"].fillna(df_analises["idade"].mean())
df_analises["idade"] = df_analises["idade"].astype(int)
df_analises["valor_compra"] = pd. to_numeric(df_analises["valor_compra"], errors="coerce")
df_analises["produto"] = df_analises["produto"].fillna("Não Informado")
df_analises = df_analises.dropna(subset='valor_compra')


display(df_analises)
display(df_analises.info())

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_cliente    15 non-null     int64
 1   nome          15 non-null     str
 2   idade         14 non-null     str
 3   cidade        14 non-null     str
 4   data_compra   15 non-null     str
 5   valor_compra  14 non-null     str
 6   produto       14 non-null     str
dtypes: int64(1), str(6)
memory usage: 972.0 bytes

None

,id_cliente,nome,idade,cidade,data_compra,valor_compra,produto
0,1,João Silva,25,São Paulo,2024-01-05 00:00:00,120.50,Notebook
1,2,Maria Souza,30,Rio De Janeiro,Não Informado,89.90,Mouse
2,3,Pedro Santos,29,Belo Horizonte,Não Informado,45.00,Teclado
4,5,Carlos Pereira,29,Curitiba,2024-01-07 00:00:00,210.00,Notebook
5,6,Juliana Alves,29,Porto Alegre,2024-01-07 00:00:00,199.99,Notebook
6,7,Bruno Costa,31,São Paulo,Não Informado,75.50,Mouse
8,9,Lucas Martins,29,Salvador,2024-01-08 00:00:00,59.90,Mouse
9,10,Patricia Gomes,35,São Paulo,Não Informado,310.00,Monitor
10,11,João Silva,25,São Paulo,2024-01-05 00:00:00,120.50,Notebook
11,12,Fernanda Dias,33,Belo Horizonte,2024-01-09 00:00:00,150.00,Notebook
12,13,Rafael Mendes,40,Não Informado,2024-01-09 00:00:00,180.75,Monitor
14,15,Gustavo Carvalho,29,Curitiba,2024-01-10 00:00:00,95.00,Não Informado

<class 'pandas.DataFrame'>
Index: 12 entries, 0 to 14
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_cliente    12 non-null     int64
 1   nome          12 non-null     str
 2   idade         12 non-null     int64
 3   cidade        12 non-null     str
 4   data_compra   12 non-null     object
 5   valor_compra  12 non-null     float64
 6   produto       12 non-null     str
dtypes: float64(1), int64(2), object(1), str(3)
memory usage: 768.0+ bytes

None